version: "3.8"

services:
  website:
    hostname: website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEBSITE_PORT}:3000"
    depends_on:
      - db
      - kong
    environment:
      - PORT=${WEBSITE_PORT}
      - SUPABASE_HOST=http://kong:8000
      - PUBLIC_SUPABASE_HOST=${APP_HOST}:8000
      - PUBLIC_SUPABASE_ANON_KEY=${SUPA_ANON_KEY}
    volumes:
      - ./website/src:/app/src
      - ./website/public:/app/public
      - ./website/astro.config.mjs:/app/astro.config.mjs
      - ./website/lang.config.json:/app/lang.config.json
      - ./website/tailwind.config.cjs:/app/tailwind.config.cjs
      - ./website/tsconfig.json:/app/tsconfig.json

  scraper:
    hostname: scraper
    build: .
    restart: unless-stopped
    ports:
      - "${SCRAPER_PORT}:3000"
    depends_on:
      - db
      - kong
    environment:
      - SCRAPER_PORT=${SCRAPER_PORT}
      - API_TOKEN=${SCRAPER_API_TOKEN}
      - CRON_EXPRESSION=${SCRAPER_CRON_EXPR}
      - SUPABASE_HOST=http://kong:8000
      - SUPABASE_SERVICE_ROLE_KEY=${SUPA_SERVICE_ROLE_KEY}
    volumes:
      - ./scraper/src:/usr/src/app/src
      - ./scraper/index.html:/usr/src/app/index.html
