create table "public"."organization_contacts" (
    "created_at" timestamp with time zone not null default now(),
    "id" bigint generated by default as identity not null,
    "id_organization" bigint,
    "description" text not null,
    "content" text not null
);


alter table "public"."organization_contacts" enable row level security;

create table "public"."organizations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "city" text not null,
    "address" text not null,
    "website" text,
    "main image" text,
    "content" text,
    "slug" text not null default ''::text
);


alter table "public"."organizations" enable row level security;

create table "public"."responsibles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "id_organization" bigint,
    "email" text not null,
    "telephone" text
);


alter table "public"."responsibles" enable row level security;

CREATE UNIQUE INDEX "Organizations_pkey" ON public.organizations USING btree (id);

CREATE UNIQUE INDEX organization_contacts_id_key ON public.organization_contacts USING btree (id);

CREATE UNIQUE INDEX organization_contacts_pkey ON public.organization_contacts USING btree (id);

CREATE UNIQUE INDEX responsibles_pkey ON public.responsibles USING btree (id);

alter table "public"."organization_contacts" add constraint "organization_contacts_pkey" PRIMARY KEY using index "organization_contacts_pkey";

alter table "public"."organizations" add constraint "Organizations_pkey" PRIMARY KEY using index "Organizations_pkey";

alter table "public"."responsibles" add constraint "responsibles_pkey" PRIMARY KEY using index "responsibles_pkey";

alter table "public"."organization_contacts" add constraint "organization_contacts_id_key" UNIQUE using index "organization_contacts_id_key";

alter table "public"."organization_contacts" add constraint "organization_contacts_id_organization_fkey" FOREIGN KEY (id_organization) REFERENCES organizations(id) not valid;

alter table "public"."organization_contacts" validate constraint "organization_contacts_id_organization_fkey";

alter table "public"."responsibles" add constraint "responsibles_id_organization_fkey" FOREIGN KEY (id_organization) REFERENCES organizations(id) not valid;

alter table "public"."responsibles" validate constraint "responsibles_id_organization_fkey";

create policy "everyone can read contacts"
on "public"."organization_contacts"
as permissive
for select
to public
using (true);


create policy "Everyone can read organizations table"
on "public"."organizations"
as permissive
for select
to public
using (true);


create policy "evryone can read this table"
on "public"."responsibles"
as permissive
for select
to public
using (true);



